### ISSUE TITLE
mapbox account reached its limits

### ISSUE THREAD

**Issue by der-On** [paesku/takka-tukka#1]
Please use openstreetmap as base layer.

**Comment by paesku** [comment]
@der-On Could you please explain the context of your issue? until now this project doesn't use any maps.

**Comment by der-On** [comment]
Ah sorry. Just followed the link to kidsle and the map used there is not showing tiles.

**Comment by paesku** [comment]
I will close this issue here. We know about the map issue from kidsle. I will create a new Issue over there
https://github.com/CodeforLeipzig/kidsle/issues

**Comment by der-On** [comment]
Thx.
